language: php

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_install:
  - phpenv config-rm xdebug.ini || return 0 # Turn off XDebug
  - mysql -e 'CREATE DATABASE datagridTest;'

install:
  - travis_retry composer install --no-progress --prefer-dist # Install dependencies

before_script:
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

script:
  - make tests # Tests

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done # Print *.actual content

jobs:
  include:
    - env: title="Lowest Dependencies 7.3"
      php: 7.3
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable
      script:
        - make tests

    - stage: Quality Assurance
      php: 7.4
      script:
        - make qa

    - stage: Test Coverage
      if: branch = master AND type = push
      php: 7.3
      script:
        - make coverage
      after_script:
        - composer global require php-coveralls/php-coveralls ^2.1.0
        - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

    - stage: Outdated Dependencies
      if: branch = master AND type = cron
      php: 7.3
      script:
        - composer outdated --direct --strict

  allow_failures:
    - php: 7.4  # todo: wait for tharos/leanmapper stable version
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
