name: "Coverage"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  coverage:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@v1
    with:
      php: "8.5"
      database: tests
      coverage: true
      make: coverage
