name: "Nette Tester"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: [ "*" ]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  test85:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@master
    with:
      php: "8.5"
      database: tests

  test84:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@master
    with:
      php: "8.4"
      database: tests

  test83:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@master
    with:
      php: "8.3"
      database: tests

  test82:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@master
    with:
      php: "8.3"
      database: tests

  testlower:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@master
    with:
      php: "8.3"
      database: tests
      composer: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"
